-- Tabela de Leads (Clientes Potenciais)
create table if not exists leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Informações de Contato
  name text,
  email text,
  phone text,
  address text,
  zip_code text, -- Added zip code
  city text,
  
  -- Detalhes do Serviço/Imóvel
  service_type text,
  frequency text,
  bedrooms numeric,
  bathrooms numeric,
  sqft numeric,
  people_count numeric, -- Quantidade de pessoas na casa
  estimated_price numeric,
  
  -- Status e Metadados
  status text default 'new',
  notes text,
  source text default 'csv_import'
);

-- Tabela de Jobs (Histórico de Limpezas)
create table if not exists jobs (
  id bigint generated by default as identity primary key,
  lead_id bigint references leads(id) on delete cascade,
  date date not null,
  team text,
  amount numeric,
  status text check (status in ('scheduled', 'completed', 'cancelled')),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (Segurança)
alter table leads enable row level security;
alter table jobs enable row level security;

-- Políticas de Acesso (Permitir tudo para anon/publico neste demo)
-- ATENÇÃO: Em produção, restrinja isso!

create policy "Allow anonymous inserts on leads" on leads for insert with check (true);
create policy "Allow anonymous selects on leads" on leads for select using (true);
create policy "Allow anonymous updates on leads" on leads for update using (true);
create policy "Allow anonymous deletes on leads" on leads for delete using (true);

create policy "Allow anonymous inserts on jobs" on jobs for insert with check (true);
create policy "Allow anonymous selects on jobs" on jobs for select using (true);
create policy "Allow anonymous updates on jobs" on jobs for update using (true);
create policy "Allow anonymous deletes on jobs" on jobs for delete using (true);
