-- Execute este código no SQL Editor do Supabase para corrigir a tabela
-- Isso garante que todas as colunas necessárias existam com os tipos corretos

-- 1. Cria a tabela se não existir
create table if not exists leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Adiciona as colunas necessárias (usamos nomes em inglês para compatibilidade com o sistema)
-- O sistema mapeia automaticamente:
-- "Nome" -> name
-- "Email" -> email
-- "Telefone" -> phone
-- "Zip" -> zip_code
-- "Type" -> frequency
-- "Bedroom" -> bedrooms
-- "Bathroom" -> bathrooms
-- "sqFt" -> sqft
-- "Pessoa" -> people_count
-- "Service" -> service_type
-- "Estimated" -> estimated_price
-- "Cidade" -> city

alter table leads add column if not exists name text;
alter table leads add column if not exists email text;
alter table leads add column if not exists phone text;
alter table leads add column if not exists zip_code text;
alter table leads add column if not exists frequency text;     -- Para a coluna "Type"
alter table leads add column if not exists bedrooms numeric;   -- Para a coluna "Bedroom"
alter table leads add column if not exists bathrooms numeric;  -- Para a coluna "Bathroom"
alter table leads add column if not exists sqft numeric;       -- Para a coluna "sqFt"
alter table leads add column if not exists people_count numeric; -- Para a coluna "Pessoa"
alter table leads add column if not exists service_type text;  -- Para a coluna "Service"
alter table leads add column if not exists estimated_price numeric; -- Para a coluna "Estimated"
alter table leads add column if not exists city text;          -- Para a coluna "Cidade"
alter table leads add column if not exists status text default 'new';
alter table leads add column if not exists notes text;

-- 3. Garante permissões (RLS)
alter table leads enable row level security;

create policy "Allow anonymous inserts on leads" on leads for insert with check (true);
create policy "Allow anonymous selects on leads" on leads for select using (true);
create policy "Allow anonymous updates on leads" on leads for update using (true);
create policy "Allow anonymous deletes on leads" on leads for delete using (true);
